### ISSUE TITLE
ProcessException: No such file or directory

### ISSUE THREAD

**Issue by BbsonLin** [thosakwe/shell#1]
I'm using this dart package in Android-x86 8.1.0.
And this error happened.

```
E/flutter (20752): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (20752): ProcessException: No such file or directory
E/flutter (20752):   Command: /bin/sh -c 'ping' '-c 5' 'demo.aiwill.tech'
E/flutter (20752): #0      Shell.start (package:shell/src/shell.dart:73:13)
E/flutter (20752): <asynchronous suspension>
E/flutter (20752): #1      CheckingState._checkConnectionWithBackendSystem (package:aiwill_vm_app/pages/prepare/checking.dart:132:27)
E/flutter (20752): <asynchronous suspension>
E/flutter (20752): #2      CheckingState._checkNetwork (package:aiwill_vm_app/pages/prepare/checking.dart:124:11)
E/flutter (20752): <asynchronous suspension>
E/flutter (20752): #3      CheckingState.initState.<anonymous closure> (package:aiwill_vm_app/pages/prepare/checking.dart:29:7)
E/flutter (20752): #4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (20752): #5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (20752): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (20752): #7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (20752): #8      Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (20752): #9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (20752): #10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (20752): #11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
E/flutter (20752): #12     CheckingState._checkSystem (package:aiwill_vm_app/pages/prepare/checking.dart)
E/flutter (20752): <asynchronous suspension>
E/flutter (20752): #13     CheckingState.initState (package:aiwill_vm_app/pages/prepare/checking.dart:28:5)
E/flutter (20752): #14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (20752): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (20752): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20752): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20752): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (20752): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20752): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20752): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (20752): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (20752): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (20752): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (20752): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20752): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20752): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (20752): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20752): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20752): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (20752): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20752): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20752): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (20752): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20752): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20752): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (20752): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20752): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20752): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (20752): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (20752): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (20752): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (20752): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (20752): #44     Element.inflateWidget (package:flutter/src/wid
```

**Comment by thosakwe** [comment]
Are you sure /bin/sh exists on Android...?

**Comment by thosakwe** [comment]
https://stackoverflow.com/questions/12056625/shell-script-in-android-gives-not-found

**Comment by BbsonLin** [comment]
Hi @thosakwe 
In my environment, `/bin/sh` does not exist ; the path should be `/system/bin/sh`

And I found out that if `runInShell` attribute set to `false`
`getExecutablePath` function in [local_process_manager.dart](
https://github.com/google/process.dart/blob/master/lib/src/interface/local_process_manager.dart#L111) will find the right path.

So, it'll be great to add an attribute called `runInShell` for `Shell` class.
Thank you.

**Comment by thosakwe** [comment]
Send a PR!

**Comment by BbsonLin** [comment]
Hi @thosakwe, 
please review #2

**Comment by thosakwe** [comment]
https://pub.dartlang.org/packages/shell/versions/1.0.1
